config/routes.rb
Vivus::Engine.routes.draw do
  get '/:section', to: 'styles#show', as: "vivus_section"
  root to: "styles#index"
end

app/models/component.rb
require 'rdiscount'

class Component
  attr_accessor :name, :section, :description, :example, :url, :source

  def display_description
    RDiscount.new(self.description, :smart, :filter_html).to_html.html_safe if self.description
  end

  def display_example
    ERB.new(example).result if self.example
  end

  def slug
    self.name.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-')
  end
end

app/models/styleguide.rb
# Takes a bunch of Stylesheets, parses them,
# and merges them into a single styleguide.
class Styleguide
  def initialize(options)
    @stylesheets = options[:stylesheets]
  end

  def generate
    @stylesheets
      .map{|stylesheet| stylesheet.parse}
      .reject{|stylesheet| stylesheet.empty?}
      .inject({}){ | accum, data |
        data.each do |section, components|
          accum[section] ||= []
          accum[section] += components
        end

        accum
      }
  end
end

app/models/stylesheet.rb
class Stylesheet
  def initialize(options)
    @file_path = options[:file_path]
    @css = options[:css]
  end

  def parse
    documentation = []

    styleguide_comments.each do |comment|
      comment = comment[1]

      name = find_name_for(comment)
      section = find_section_for(comment)
      description = find_description_for(comment)
      example = find_example_for(comment)
      url = find_url_for(comment)

      if name.present? || section.present? || description.present? || example.present? || url.present?
        component = Component.new

        component.source = @file_path

        component.name = name if name
        if section
          component.section = section
        else
          component.section = name
        end

        component.description = description if description
        component.example = example if example
        component.url = url if url

        documentation << component
      end
    end
    group_by_section(documentation)
  end

  private

  def group_by_section documentation
    documentation.sort_by(&:section).group_by(&:section).each do |key, group|
      group.sort!{|a,b| a.name.downcase <=> b.name.downcase }
    end
  end

  def find_name_for comment
    regex = /\[Name\](.*?)(\[Section\]|\[Description\]|\[Example\]|\[Url\]|\*\/|\z)/m
    result = scan_comment(comment, regex)
    if result.present?
      result.first[1].strip
    end
  end

  def find_section_for comment
    regex = /\[Section\](.*?)(\[Name\]|\[Description\]|\[Example\]|\[Url\]|\*\/|\z)/m
    result = scan_comment(comment, regex)
    if result.present?
      result.first[1].strip
    end
  end

  def find_description_for comment
    regex = /\[Description\](.*?)(\[Name\]|\[Section\]|\[Example\]|\[Url\]|\*\/|\z)/m
    result = scan_comment(comment, regex)
    if result.present?
      result.first[1].strip
    end
  end

  def find_example_for comment
    regex = /\[Example\](.*?)(\[Name\]|\[Section\]|\[Description\]|\[Url\]|\*\/|\z)/m
    result = scan_comment(comment, regex)
    if result.present?
      result.first[1].strip
    end
  end

  def find_url_for comment
    regex = /\[Url\](.*?)(\[Name\]|\[Section\]|\[Description\]|\[Example\]|\*\/|\z)/m
    result = scan_comment(comment, regex)
    if result.present?
      result.first[1].strip
    end
  end

  def styleguide_comments
    regex = /\/\*\*(.*?)\*\*\//m
    scan_comment(@css, regex)
  end

  def scan_comment text, regex
    text.to_enum(:scan, regex).map { Regexp.last_match }
  end
end

app/controllers/vivus/application_controller.rb
module Vivus
  class ApplicationController < ActionController::Base
  end
end

app/controllers/vivus/styles_controller.rb
# Controller for dsiplaying the documentation for the styles
class Vivus::StylesController < Vivus::ApplicationController
  def index
    gather_stylesheets
  end

  def show
    gather_stylesheets
  end

  private

  def gather_stylesheets

    sprockets = Rails.application.assets

    @css_paths = Rails.application.config.assets.precompile.select do |item|
      item.is_a?(String) && item[-4,4] == ".css"
    end
    stylesheets = @css_paths.map{|file_path| Stylesheet.new(file_path: file_path, css: sprockets[file_path].source)}

    styleguide = Styleguide.new(stylesheets: stylesheets)
    @stylesheets = styleguide.generate
  end

  def is_a_file? file
    File.file?(file)
  end
end

app/views/layouts/vivus/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vivus</title>
  <%= stylesheet_link_tag    "vivus/application", :media => "all" %>
  <%= javascript_include_tag "vivus/application" %>

  <% @css_paths.each do |path| %>
    <% if path.match(/print/).nil? %>
      <%= stylesheet_link_tag path, :media => "all" %>
    <% else %>
      <%= stylesheet_link_tag path, :media => "print" %>
    <% end %>
  <% end %>

  <%= csrf_meta_tags %>
</head>
<body id="vivus">
  <%= yield %>
</body>
</html>

app/views/vivus/styles/_component.html.erb
<li class='vivus-component'>

  <div class="vivus-documentation">
    <h2 class="vivus-name"><%= component.name %></h2>
    <%= component.display_description %>
  </div>

  <% if component.example.present? %>
    <nav class="vivus-tabbed">
      <a href="#vivus-example" class="vivus-tab vivus-active">Example</a>
      <a href="#vivus-code" class="vivus-tab">Code</a>
    </nav>

    <div class="vivus-example vivus-block vivus-block-opened">
      <%= component.display_example.html_safe %>
    </div>

    <div class="vivus-code vivus-block ">
      <em class="vivus-source">From <%= component.source %></em>
      <pre><%= component.display_example %></pre>
    </div>
  <% end %>
</li>

app/views/vivus/styles/_nav.html.erb
<nav id="vivus-navigation">
  <ul>
    <% @stylesheets.each do |group| %>
      <% section = group[0] %>
      <% section_slug = section.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-') %>
      <% components = group[1] %>

      <li class="h1 <%= "active" if section.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-') == params[:section] %>">
        <%= link_to section, vivus_section_path(section_slug) %>

        <% if components.present? %>
          <ul>
            <% components.uniq{|c| c.name}.each do |component| %>
              <li class="h2">
                <%= link_to component.name, vivus_section_path(section_slug, anchor: component.slug) %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/vivus/styles/index.html.erb
<%= render partial: "nav" %>
<div id="vivus-body">
  <ul class="vivus-sections">
      <li class="vivus-section">
        <h2></h2>
        <h1 class="vivus-section-title">Let's begin!</h1>

        <p>Above each block of code in your CSS, start documenting your styleguide by writing comments.</p>
        <p>Use the below example as a starting point.</p>
        <pre>
/**
[Name] The name of the component (e.g. Success Buttons)
[Section] A section that groups components together (e.g. Buttons)
[Description]

Write some documentation explaining the use / concept of the CSS
you've got below. This bit will be markdown rendered.

- You can use three backticks (`) to indicate a code block
- ```&lt;div class="example"&gt;&lt;/div&gt;```
- Code blocks will be syntax highlighted

When you've documented it nicely, use the Example markers to
indicate a block of HTML that uses the CSS.

Keeps your documentation right near the CSS.
So, if you update / refactor the CSS, update the HTML example if
need be.

[Example]
&lt;div class="example"&gt;
  &lt;a href="#" class="button"&gt;Some text&lt;a&gt;
&lt;/div&gt;
[Url] A web address pointing to further documentation / example (optional)
**/
        </pre>
      </li>
  </ul>
</div>

app/views/vivus/styles/show.html.erb
<%= render partial: "nav" %>
<div id="vivus-body">
  <ul class="vivus-sections">

    <% @stylesheets.select{ |section| section.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-') == params[:section]}.each do |title, components| %>

      <li class="vivus-section">
        <h1 class="vivus-section-title"><%= title %></h1>
        <ul class="vivus-components">
          <%= render partial: "component", collection: components.uniq{|c| c.name} %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>